# fly.toml app configuration file generated for daily-set-realtime on 2025-09-10T05:44:18-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'daily-set-realtime'
primary_region = 'iad'

[build]

[env]
  REALTIME_ADDR = ':8081'

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
