name: Backend CI

on:
  push:
    branches: [main]
    paths:
      - "app/**"
      - "tests/**"
      - "requirements.txt"
      - "pytest.ini"
      - ".github/workflows/backend.yml"
  pull_request:
    branches: [main]
    paths:
      - "app/**"
      - "tests/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests with coverage
        run: pytest -q --cov=app --cov-report=term-missing --cov-report=xml

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          flags: backend
          fail_ci_if_error: false
